name: Trigger auto deployment for nicolenders-prod-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nicolenders-prod-web-AutoDeployTrigger-0ca5fd12-ab86-40bd-9dfc-2d907aaae00e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NICOLENDERSPRODWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NICOLENDERSPRODWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NICOLENDERSPRODWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: nicolendersacr.azurecr.io
          registryUsername: ${{ secrets.NICOLENDERSPRODWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NICOLENDERSPRODWEB_REGISTRY_PASSWORD }}
          containerAppName: nicolenders-prod-web
          resourceGroup: nicolenders-rg
          imageToBuild: nicolendersacr.azurecr.io/nicolenders-prod-web:${{ github.sha }}
